[package]
name = "ChantGPT"
version = "0.1.0"
edition = "2021"

[dependencies]

clap = { version = "4.5.4", features = ["derive"] }
anyhow = "1.0.81"
tokenizers = "0.19.1"
ort = "=2.0.0-rc.1"
ndarray = "0.15.6"
num-traits = "0.2.18"
log = "0.4.21"
rand = "0.8.5"
hound = "3.5.1"
